name: Build Site

on:
  push:
    paths:
      - '_vera/**'
      - '_weblogs/**'
      - '_dialogues/**'
      - '_sessions/**'
      - '_templates/**'
      - 'build.py'
      - 'index.html'
      - '.github/workflows/build.yml'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Diagnostic - Show trigger event
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Ref name: ${{ github.ref }}"
          echo "Repository: ${{ github.repository }}"

      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Pre-build validation
        run: |
          set -euo pipefail
          echo "Current directory: $(pwd)"
          required_dirs=( _vera _weblogs _dialogues _sessions _templates vera weblogs dialogues sessions )
          for dir in "${required_dirs[@]}"; do
            echo "Checking directory: $dir"
            if [ ! -d "$dir" ]; then
              echo "::error::Required directory missing: $dir"
              exit 1
            fi
          done
          if [ ! -f index.html ]; then
            echo "::error::index.html not found"
            exit 1
          fi

      - name: Run build script
        run: |
          set -euo pipefail
          echo "Running build.py"
          python3 build.py

      - name: Post-build validation
        run: |
          set -euo pipefail
          check_file() {
            local path=$1
            local min_size=$2
            if [ ! -f "$path" ]; then
              echo "::error::Required file missing: $path"
              exit 1
            fi
            local size
            size=$(stat -c%s "$path")
            if [ "$size" -lt "$min_size" ]; then
              echo "::error::File too small: $path (${size} bytes)"
              exit 1
            fi
          }
          check_file index.html 500
          check_file vera/log.html 100

      - name: Configure git
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Stage generated files
        run: |
          set -euo pipefail
          git add -f build.log index.html
          git add -f dialogues/ weblogs/ sessions/ vera/
          echo "Staged files:" || true
          git diff --name-only --cached || true

      - name: Commit and push if changed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
          git commit -m "Rebuild site from content changes"
          git push origin HEAD:main
          echo "Push complete"
          git diff --name-only HEAD^ HEAD
