name: Build Site

on:
  push:
    paths:
      - '_posts/**'
      - '_dialogues/**'
      - '_raw-data/**'
      - '_templates/**'
      - 'build.ps1'
      - 'index.html'
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      
    - name: Run build script
      shell: pwsh
      run: |
        ./build.ps1
        
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add weblogs/ dialogues/ raw-data/ index.html
        git commit -m "Build site from content changes" || exit 0
        git push origin HEAD:main 