name: Build Site

on:
  push:
    paths:
      - '_posts/**'
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Run build script
      shell: pwsh
      run: |
        ./build.ps1
        
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add weblogs/ index.html
        git commit -m "Build site from new posts" || exit 0
        git push 