name: Build Site

on:
  push:
    paths:
      - '_weblogs/**'
      - '_dialogues/**'
      - '_raw-data/**'
      - '_vera/**'
      - '_templates/**'
      - 'build.ps1'
      - 'index.html'
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0  # Get all history for proper file comparison
      
    - name: Run build script
      shell: pwsh
      run: |
        Write-Host "Files changed in this push:"
        git diff --name-only HEAD^ HEAD
        ./build.ps1
        
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: pwsh
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add weblogs/ dialogues/ vera/ raw-data/ index.html
        git status
        git diff --staged --quiet || (git commit -m "Rebuild site from content changes" && git push origin HEAD:main)
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE } else { exit 0 } 