name: Build Site

on:
  push:
    paths:
      - '_vera/**'
      - '_weblogs/**'
      - '_dialogues/**'
      - '_raw-data/**'
      - '_templates/**'
      - 'build.ps1'
      - 'index.html'
      - '.github/workflows/build.yml'
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    
    steps:
    - name: Diagnostic - Show trigger event
      shell: pwsh
      run: |
        Write-Host "Event name: ${{ github.event_name }}"
        Write-Host "Ref name: ${{ github.ref }}"
        Write-Host "Repository: ${{ github.repository }}"
    
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
        persist-credentials: true
    
    - name: Diagnostic - Pre-build state
      shell: pwsh
      run: |
        Write-Host "Current directory: $pwd"
        Write-Host "`nSource file contents (_vera/log.txt):"
        if (Test-Path "_vera/log.txt") {
            Get-Content "_vera/log.txt"
        } else {
            Write-Host "Source file not found!"
        }
        Write-Host "`nCurrent HTML file (vera/log.html):"
        if (Test-Path "vera/log.html") {
            Get-Content "vera/log.html"
        } else {
            Write-Host "HTML file not found!"
        }
        Write-Host "`nGit status:"
        git status
        Write-Host "`nChanged files in this push:"
        git diff --name-only HEAD^ HEAD
    
    - name: Run build script
      shell: pwsh
      run: |
        Write-Host "Running build.ps1"
        ./build.ps1
        
    - name: Diagnostic - Post-build state
      shell: pwsh
      run: |
        Write-Host "`nNew HTML contents (vera/log.html):"
        if (Test-Path "vera/log.html") {
            Get-Content "vera/log.html"
        } else {
            Write-Host "HTML file not found after build!"
        }
        Write-Host "`nGit status after build:"
        git status
        Write-Host "`nChanges from build:"
        git diff --stat
        
    - name: Configure git
      shell: pwsh
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        Write-Host "Git config:"
        git config --list
        
    - name: Stage changes
      shell: pwsh
      run: |
        Write-Host "Adding all generated files..."
        git add -f vera/log.html weblogs/ dialogues/ raw-data/ index.html
        Write-Host "`nGit status after staging:"
        git status
        
    - name: Commit and push if changed
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: pwsh
      run: |
        if (git diff --staged --quiet) {
            Write-Host "No changes to commit"
            exit 0
        } else {
            Write-Host "Changes found, committing..."
            git commit -m "Rebuild site from content changes"
            Write-Host "`nPushing changes..."
            git push origin HEAD:main
            Write-Host "`nPush complete"
        } 